routes/web.php
<?php
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Web'], function () 
{
	// Check if a logged in user is already registered in SSO. Else redirect to force register first
	Route::group(['middleware' => ['ssoregistered']], function() {
		Route::get('/', 'HomeController@index')->name('home');
		Route::get('/?showlogin', 'HomeController@index')->name('login');

		Route::get('/terms', 'HomeController@termsPage')->name('terms');
		Route::get('/privacy', 'HomeController@privacyPage')->name('privacy');
		Route::get('/exchange', 'HomeController@pointsExchangePage')->name('points_exchange');

		Route::get('/announcements', 'HomeController@announcementsPage')->name('announcements');
		Route::get('/announcements/{announcementsId}/{announcementsSlug?}', 'AnnouncementsController@announcementsDetailPage')->name('announcements_detail');

		//Payment
		Route::get('/payment/payment_product_detail', 'PaymentController@paymentProductDetail')->name('payment_product_detail');
		Route::get('/payment/payment_payment_detail', 'PaymentController@paymentPaymentDetail')->name('payment_payment_detail');
		Route::get('/payment/payment_complete', 'PaymentController@paymentComplete')->name('payment_complete');

		// Partners
		Route::get('/partners/{partnerId}/{partnerSlug?}/profile', 'PartnerController@earnPartnerProfilePage')->name('partner_profile');
		Route::get('/partners/{partnerId}/{partnerSlug}/offer/{offerId}', 'PartnerController@earnPartnerOfferPage')->name('partner_offer');
		Route::get('/partners/{partnerId}/{partnerSlug?}', 'PartnerController@earnPartnerDetailPage')->name('partner_detail');
		
	    //Memberships
		Route::get('/member/register', 'MemberController@register');
		Route::get('/member/profile', 'MemberController@profile');
		Route::get('/member/survey_panelist', 'MemberController@surveyPanelistPage');
		
		Route::get('/shop', 'MemberController@shopOnline')->name('shoponline_list');
		Route::get('/shop/{key}', 'MemberController@shopOnlineFilter')->name('shoponline_filter');
		Route::get('/shop-redirect', 'MemberController@shopOnlineRedirect')->name('shoponline_redirect');

		Route::get('/earn_bpoints', 'MemberController@earnPoints')->name('earn_bpoints');
		Route::get('/redeem_bpoints', 'MemberController@redeemPoints')->name('redeem_bpoints');
		Route::get('/membership', 'MemberController@membershipPage')->name('membership');

		// All following routes require login and already registered
		Route::group(['middleware' => ['auth']], function() {
			Route::get('/member/profile', 'MemberController@profile')->name('member_profile');
			Route::post('/member/set_primary_card', 'MemberController@setPrimaryCard')->name('set_primary_card');
			Route::post('/member/virtual_card_register', 'MemberController@virtualCardRegister')->name('register_virtual_card');
			Route::post('/member/update_contact', 'MemberController@updateContact')->name('update_contact');
			Route::get('/member/points_history', 'MemberController@pointsHistroy');

			//Convert points API
			Route::post('/exchange', 'MemberController@pointsConvert');

			// Card related APIs
			Route::post('/card/link', 'CardController@linkCard');
			Route::match(['get', 'post'], '/member/network_of_partner', 'MemberController@networkOfPartner')->name('network_of_partner');
		});
	});

	
	
	// All following routes require only logged in user, but not registered SSO.
	Route::group(['middleware' => ['auth']], function() {
		Route::any('/member/verify_mobile', 'MemberController@verifyMobile')->name('member_verify_mobile');
		Route::any('/member/card_register', 'MemberController@cardRegister')->name('member_register_sso');
	});

	Route::match(['get', 'post'], '/support', 'HomeController@supportPage')->name('support');

	//Dummy test page
	if(config('app.env') <> 'production') {
		Route::get('/payment/dummy','PaymentController@dummy' );
	}

	Route::get('/payment/summary','PaymentController@order');
	Route::any('/payment/capture','PaymentController@capture' );

	//Convert points API
	Route::post('/exchange', 'MemberController@pointsConvert');

});

//Route::get('/home', 'HomeController@index')->name('home');

//Auth and Socialites login
Route::group(['namespace' => 'Auth'], function () 
{
	Route::get('/auth/{provider}', 'AuthController@redirectToProvider');
	Route::get('/auth/{provider}/callback', 'AuthController@handleProviderCallback');

	Route::get('/logout', 'AuthController@logout');
	Route::post('/member_login','AuthController@memberLogin');
	Route::post('/member_register', 'AuthController@memberRegister');
	// Route::post('/member_register', function(){ dd("TESYSETSETSE"); });

	Route::get('/account/activation/{user_id}/{activation_code}', 'AuthController@memberActivation');

	Route::post('/test_form', 'TestFormController@test');
});

// uMobile and old campaigns
Route::group(['namespace' => 'Legacy'], function () 
{
	Route::any('/umobile/{filename}', 'UmobileController@all')->where('filename', '.*');

	// Insurance pages
	Route::any('/insurance-auto.php', 'InsuranceAutoController@index')->name('insurance_auto_index');
	Route::any('/insurance-fraudulent-cover.php', 'InsuranceFraudulentController@index')->name('insurance_fraudulent_index');
	Route::any('/insurance-travel.php', 'InsuranceTravelController@index')->name('insurance_travel');
	Route::any('/insurance.php', 'InsuranceController@index')->name('insurance_index');

	// Shoponline SG
	Route::any('/shop-online-sg.php', 'ShoponlineController@index')->name('shoponline_sg_index');
	Route::any('/shop-online-sg-check.php', 'ShoponlineController@check')->name('shoponline_sg_check');
	Route::any('/shop-online-sg-redirect.php', 'ShoponlineController@redirect')->name('shoponline_sg_redirect');

	// Insurance microsites (with db too)
	Route::any('/insurance-auto/{filename}', 'InsuranceAutoController@all')->where('filename', '.*')->name('insurance_auto');
	Route::any('/insurance-fraudulent-cover/{filename}', 'InsuranceFraudulentController@all')->where('filename', '.*')->name('insurance_fraudulent');
});

// To remove the following after test
if (App::environment(['local', 'development', 'staging'])) {
	Route::get('/ilyas', 'Web\IlyasController@testilyas');
	Route::get('/testmylms', 'Web\IlyasController@testmylms');
}

app/Merchant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Rinvex\Categories\Traits\Categorizable;
use Illuminate\Support\Str;
use App\Category;
use \Storage;
use App\Traits\StorageImageResolver;

class Merchant extends Model
{
	use Categorizable, StorageImageResolver;

	protected $appends = ['profile_url'];

	/**
	 * Relation to merchant_offers
	 *
	 */
	public function offers()
	{
		return $this->hasMany('App\MerchantOffer', 'merchant_id');
	}

	/**
	 * Relation to merchant_offers for active offers only
	 *
	 */
	public function activeOffers()
	{
		return $this->offers()->active(true);
	}

	/**
	 * Relation to merchant_outlets
	 *
	 */
	public function outlets()
	{
		return $this->hasMany('App\MerchantOutlet', 'merchant_id');
	}

	/**
	 * Attribute for full url for merchant logo
	 *
	 */
	public function getLogoImageAttribute()
	{
		return $this->resolveImage($this->logo_url);
	}

	/**
	 * Attribute for full url for merchant profile top banner
	 *
	 */
	public function getProfileBannerImageAttribute()
	{
		return $this->resolveImage($this->profile_banner_url);
	}

	/**
	 * Attribute for full url for merchant profile footer banner
	 *
	 */
	public function getProfileFooterBannerImageAttribute()
	{
		return $this->resolveImage($this->profile_footer_banner_url);
	}

	/**
	 * Attribute merchant name slugified
	 *
	 */
	public function getSlugAttribute()
	{
		return Str::slug($this->name);
	}

	/**
	 * Attribute for merchant slug for better SEO url
	 *
	 */
	public function getSlugUrlAttribute()
	{
		return $this->id . '/' . $this->slug;
	}

	/**
	 * Attribute for merchant slug for better SEO url
	 *
	 */
	public function getProfileUrlAttribute()
	{
		return route('partner_profile', [ $this->id, $this->slug ]);
	}

	/**
	 * Attribute for merchant slug for better SEO url
	 *
	 */
	public function getConditionalUrlAttribute()
	{
		$activeOffers = $this->activeOffers;
		$offerCount = $activeOffers->count();

		if ($offerCount == 1) {
			return route('partner_offer', [$this->id, $this->slug, $activeOffers->first()->id]);
		}

		if ($offerCount > 1) {
			return route('partner_profile', [$this->id, $this->slug]);
		}

		return route('partner_detail', [$this->id, $this->slug]);
	}
}

resources/views/web/pages/earn_points.blade.php
@extends('web.master')

@section('content')

<?php 
$collections = [
//    'earn-points' => [
//            'name' => 'Earn BPoints with these exciting brands',
//            'items' => [
//                [
//                    'partner' => 'caltex',
//                    'image' => '8e4b3378e00274c3ddd2fac0129609dd.png',
//                    'company' => 'Caltex',
//                    'title' => '3X Points When You Fill Fuel With Us!',
//                    'validDate' => '31st December 2018',
//                    'actionTitle' => 'Earn',
//                ],
//                [
//                    'partner' => 'berjaya',
//                    'image' => 'marc-babin-334972-unsplash.png',
//                    'company' => 'Berjaya GROUP',
//                    'title' => 'Complimentary Stay when you have a long offer line',
//                    'point' => 'RM1 = 1BPoint',
//                    'validDate' => '31st December 2018',
//                    'actionTitle' => 'Earn',
//                ],
//                [
//                    'partner' => 'zalora',
//                    'image' => '205bbd329dd1fbc81d918d670996c429.png',
//                    'company' => 'ZALORA',
//                    'title' => 'Spend at Zalora, get 2X Points for every RM spent!',
//                    'validDate' => '31st December 2018',
//                    'actionTitle' => 'Earn',
//                ]
//            ]
//    ],
//    'earn-brand' => [
//            'name' => 'Earn BPoints with our Partners',
//            'items' => [
//                [
//                    'partner' => 'rakuten',
//                    'image' => 'rkt.png',
//                    'point' => 'RM 1 = 1 BPOINT',
//                ],
//                [
//                    'partner' => '711',
//                    'image' => '711-logo.png',
//                    'point' => 'RM 1 = 1 BPOINT',
//                ],
//                [
//                    'partner' => '11street',
//                    'image' => '11street-logo.png',
//                    'point' => 'RM 1 = 1 BPOINT',
//                ],
//                [
//                    'partner' => 'aeon',
//                    'image' => 'e128d0669a09965286dc8ed12d47e885.png',
//                    'point' => 'RM 1 = 1 BPOINT',
//                ]
//            ]
//    ],
    'collect-points' => [
            'name' => 'Get the most out of B Infinite',
            'items' => [
                [
                    'ribbon' => 'Fasttrack your BPoints',
                    'image' => '8e4b3378e00274c3ddd2fac0129609dd.png',
                    'title' => 'Collect TRIPLE POINTS when you fill fuel at Caltex!',
                    'actionTitle' => 'LEARN MORE',
                ],
                [
                    'ribbon' => 'Collect Bonus Points',
                    'image' => 'marc-babin-334972-unsplash.png',
                    'title' => 'Look out for BONUS POINTS deals all around Tesco, in emails, deals and coupons',
                    'actionTitle' => 'VIEW ALL DEALS',
                ],
                [
                    'ribbon' => 'Be Rewarded',
                    'image' => 'as.png',
                    'title' => 'Reward your healthy habits, collect and redeem points with our health partners',
                    'actionTitle' => 'VIEW HEALTH PARTNERS',
                ]
            ]
    ]
];

//dd($merchants);
?>

<section class="earn-points">
    <section class="content gray-2">
        <div class="container">
            <div class="header row mx-0 mb-2">
                <span>Earn <span class="font-bold">BPoints</span></span>
            </div>

            <div class="row mx-0">
                <div class="col-lg-8">
                    <p>Our extensive network of Partners includes some of the largest household names, so that you can
                        collect
                        points on things you do everyday. There are so many other ways for you to collect and
                        accelerate
                        your
                        points, all you need is your B Infinite virtual card.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="content2 menu">
        <div class="container">
            @include('web.include.category_icon_menu')
        </div>
    </section>

    <section class="content gray earn pb-5">
        <div class="container pt-5">
            @isset($offers)
            @include('web.components.partner_offers_collection', 
                ['key' => 'earn-points', 'collection' => ['name' => 'Earn BPoints with these exciting brands', 'items' => $offers]])
            @endisset
        </div>

        <div class="container">
            <div class="header row align-items-end justify-content-between pt-5">
                <span>Earn BPoints with our Partners</span>
                <a class="btn btn-outline-blue" href="/partners/trec/offer">VIEW ALL</a>
            </div>

            <div class="parent">
                @foreach ($merchants as $merchant)
                <div class="earn-brand">
                    <a href="{{ $merchant->conditionalUrl }}">
                        <div class="ribbon clearfix">
                            <div class="ribbon-terms">{{ $merchant->points_earning_listing }}</div>
                        </div>
                        <div class="overlay"></div>
                        <h3 style="{{ BH::backgroundImage($merchant->logo_image) }}"></h3>
                    </a>
                </div>
                {{-- <div class="earn-brand">
                    <a href="{{ route('partner_detail', '711') }}">
                <div class="ribbon clearfix">
                    <div class="ribbon-terms">RM 1 = 1 BPOINT</div>
                </div>
                <div class="overlay"></div>
                <h3 style="{{ BH::backgroundImage('711-logo.png') }}"></h3>
                </a>

            </div>
            <div class="earn-brand">
                <a href="{{ route('partner_detail', '11street') }}">
                    <div class="ribbon clearfix">
                        <div class="ribbon-terms">RM 1 = 1 BPOINT</div>
                    </div>
                    <div class="overlay"></div>
                    <h3 style="{{ BH::backgroundImage('11street-logo.png') }}"></h3>
                </a>
            </div>
            <div class="earn-brand">
                <a href="#">
                    <div class="ribbon clearfix">
                        <div class="ribbon-terms">RM 1 = 1 BPOINT</div>
                    </div>
                    <div class="overlay"></div>
                    <h3 style="{{ BH::backgroundImage('e128d0669a09965286dc8ed12d47e885.png') }}"></h3>
                </a>
            </div> --}}
            @endforeach
        </div>
        </div>
    </section>

    <section class="content">
        <div class="container pt-2">
            @include('web.components.collect_points_collection', ['key' => 'collect-points', 'collection' =>
            $collections['collect-points']])
        </div>
        <div class="container py-5">
            @include('web.include.ads')
        </div>
    </section>
</section>

@endsection

@section('custom_js')
<script>
    $('.single-slick').slick({
        dots: true,
        infinite: true,
        speed: 300,
        slidesToShow: 1,
        centerMode: true,
        variableWidth: true
    });

    $('.responsive').fadedSlick();

    $(document).ready(function () {
        $('#media').carousel({
            pause: true,
            interval: false,
        });
    });

</script>
@endsection

resources/views/web/pages/home.blade.php
@extends('web.master')

@section('content')

<?php 
$collections = [
    'collect-points' => [
            'name' => 'Get the most out of B Infinite',
            'items' => [
                [
                    'ribbon' => 'Fasttrack your BPoints',
                    'image' => '8e4b3378e00274c3ddd2fac0129609dd.png',
                    'title' => 'Collect TRIPLE POINTS when you fill fuel at Caltex!',
                    'actionTitle' => 'LEARN MORE',
                ],
                [
                    'ribbon' => 'Collect Bonus Points',
                    'image' => 'marc-babin-334972-unsplash.png',
                    'title' => 'Look out for BONUS POINTS deals all around Tesco, in emails, deals and coupons',
                    'actionTitle' => 'VIEW ALL DEALS',
                ],
                [
                    'ribbon' => 'Be Rewarded',
                    'image' => '205bbd329dd1fbc81d918d670996c429.png',
                    'title' => 'Reward your healthy habits, collect and redeem points with our health partners',
                    'actionTitle' => 'VIEW HEALTH PARTNERS',
                ]
            ]
    ],
    'latest-deals' => [
            'name' => 'Latest Deals',
            'items' => [
                [
                    'image' => '8e4b3378e00274c3ddd2fac0129609dd.png',
                    'company' => 'Caltex',
                    'title' => 'Example of a deal or promotion',
                    'point' => 'RM1 = 1BPoint',
                    'validDate' => '31st December 2018',
                ],
                [
                    'image' => 'marc-babin-334972-unsplash.png',
                    'company' => 'Berjaya GROUP',
                    'title' => 'Complimentary stay when you have a long offer line',
                    'point' => 'RM1 = 1BPoint',
                    'validDate' => '31st December 2018',
                ],
                [
                    'image' => '205bbd329dd1fbc81d918d670996c429.png',
                    'company' => 'ZALORA',
                    'title' => '15% OFF',
                    'point' => 'RM1 = 1BPoint',
                    'validDate' => '31st December 2018',
                ]
            ]
    ],
    'top-picks' => [
            'name' => 'Top Picks',
            'items' => [
                [
                    'image' => '8e4b3378e00274c3ddd2fac0129609dd.png',
                    'company' => 'Caltex',
                    'title' => 'Example of a deal or promotion',
                    'point' => 'RM1 = 1BPoint',
                    'validDate' => '31st December 2018',
                ],
                [
                    'image' => 'marc-babin-334972-unsplash.png',
                    'company' => 'Berjaya GROUP',
                    'title' => 'Complimentary stay when you have a long offer line',
                    'point' => 'RM1 = 1BPoint',
                    'validDate' => '31st December 2018',
                ],
                [
                    'ribbon' => '5 days left!',
                    'image' => '205bbd329dd1fbc81d918d670996c429.png',
                    'company' => 'ZALORA',
                    'title' => '15% OFF',
                    'point' => 'RM1 = 1BPoint',
                    'validDate' => '31st December 2018',
                ]
            ]
    ]
]
?>

<section class="home">
    <div class="container-fluid">
        @include('web.include.hero_slider')

        @include('web.include.member_stats')
    </div>

    <section class="content gray">
        <div class="container pt-2">
            @include('web.include.ads')

            @if (Auth::check())
            @include('web.components.collect_points_collection', ['key' => 'collect-points', 'collection' =>
            $collections['collect-points']])
            @endif
        </div>
        <div class="container-fluid pb-5">
            @if (!Auth::check() && isset($collections['latest-deals']))
            @include('web.components.slider_collection', ['key' => 'latest-deals', 'collection' =>
            $collections['latest-deals']])
            @endif

            @isset($collections['top-picks'])
            @include('web.components.slider_collection', ['key' => 'top-picks', 'collection' =>
            $collections['top-picks']])
            @endisset
        </div>
    </section>

    <section class="content py-100">
        <div class="container">
            @include('web.include.ads')

            @include('web.include.partners')
        </div>
    </section>

    <section class="content gray py-100">
        <div class="container">
            @include('web.include.redeemables')
        </div>
    </section>
</section>

@endsection

@section('custom_js')
<script>
    $(document).ready(function () {
        // $('#media').carousel({
        //     pause: true,
        //     interval: false,
        // });

        // $('.single-slick').slick({
        //     dots: true,
        //     infinite: true,
        //     speed: 300,
        //     slidesToShow: 1,
        //     centerMode: true,
        //     variableWidth: true
        // });

        $('.faded-slick').each(function () {
            $(this).fadedSlick();
        });

        $('#carousel-generic .slider').redeemablesSlider(
            $('.redeem-suggestions a[data-slide="prev"]'),
            $('.redeem-suggestions a[data-slide="next"]'),
            $('.redeem-suggestions .redeem-suggestions-carousel-page'),
        );
    });

</script>
@endsection

resources/views/web/pages/points_exchange.blade.php
@extends('web.master')

@section('content')

<?php 
$collections = [
    'points-exchange' => [
            'name' => 'Convert to BPoints',
            'items' => [
                [
                    'partner' => 'mbb',
                    'image' => 'mbb-logo.png',
                    'point' => '3,000 POINTS = 1,000 BPOINTS',
                    'actionTitle' => 'convert',
                    'actionUrl' => 'javascript:void(0);',
                    'brandName' => 'Maybank Loyalty',
                    'fieldIdTitle' => 'MAYBANK LOYALTY ID',
                    'fieldIdName' => 'maybankLoyaltyNumber',
                ],
                [
                    'partner' => 'cimb',
                    'image' => 'cimb-logo.png',
                    'point' => '3,000 POINTS = 1,000 BPOINTS',
                    'actionTitle' => 'convert',
                    'actionUrl' => 'javascript:void(0);',
                    'brandName' => 'CIMB',
                    'fieldIdTitle' => 'CIMB POINTS ID',
                    'fieldIdName' => 'cimbPointsId',
                ],
                [
                    'partner' => 'aab',
                    'image' => 'aab-logo.png',
                    'point' => '3,000 POINTS = 1,000 BPOINTS',
                    'actionTitle' => 'convert',
                    'actionUrl' => 'javascript:void(0);',
                    'brandName' => 'AirAsia BIG',
                    'fieldIdTitle' => 'AIRASIA BIG MEMBER ID',
                    'fieldIdName' => 'bigMemberId',
                ],
                [
                    'partner' => 'kris_sg',
                    'image' => 'kris_sg-logo.png',
                    'point' => '3,000 POINTS = 1,000 BPOINTS',
                    'actionTitle' => 'convert',
                    'actionUrl' => 'javascript:void(0);',
                    'brandName' => 'KrisFlyer',
                    'fieldIdTitle' => 'KRISFLYER NUMBER',
                    'fieldIdName' => 'krisflyerNumber',
                ]
            ]
    ],
    'collect-points' => [
            'name' => 'Get the most out of B Infinite',
            'items' => [
                [
                    'ribbon' => 'Fasttrack your BPoints',
                    'image' => '8e4b3378e00274c3ddd2fac0129609dd.png',
                    'title' => 'Collect TRIPLE POINTS when you fill fuel at Caltex!',
                    'actionTitle' => 'LEARN MORE',
                ],
                [
                    'ribbon' => 'Collect Bonus Points',
                    'image' => 'marc-babin-334972-unsplash.png',
                    'title' => 'Look out for BONUS POINTS deals all around Tesco, in emails, deals and coupons',
                    'actionTitle' => 'VIEW ALL DEALS',
                ],
                [
                    'ribbon' => 'Be Rewarded',
                    'image' => 'as.png',
                    'title' => 'Reward your healthy habits, collect and redeem points with our health partners',
                    'actionTitle' => 'VIEW HEALTH PARTNERS',
                ]
            ]
    ]
];
?>

<section class="earn-points">
    <section class="content gray exchange">
        <div class="container">
            @isset($collections['points-exchange'])
            @include('web.components.earn_brand_collection', ['key' => 'points-exchange', 'collection' =>
            $collections['points-exchange'], 'isEnableViewAll' => false])
            @endisset

            <div class="button-container text-center">
                <a class="btn btn-outline-blue" href="/#">LOAD MORE</a>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="container pt-2">
            @include('web.components.collect_points_collection', ['key' => 'collect-points', 'collection' =>
            $collections['collect-points']])
        </div>
        <div class="container py-5">
            @include('web.include.ads')
        </div>
    </section>
</section>

@include('web.include.dialog.convert_bpoints_dialog')

@endsection

@section('custom_js')
<script>
    $(document).ready(function () {
        $("[id^=unlink]").click(function () {
            $(this).closest(".card").children(".unlinked").addClass("active");
        });
    });

    function setupConversionForm(partner, brandName, fieldIdTitle, fieldIdName) {
        $("#partner").val(partner);
        $("#partner_name").val(brandName);

        $('brandName').text(brandName);
        $('#memberUID').text(fieldIdTitle);
        $('input#memberUIDNumber').attr('name', fieldIdName);
    }

</script>
@endsection